name: credit_Fraud
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - alabaster=0.7.12
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfgv=3.3.1
  - chardet=5.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - commonmark=0.9.1
  - configupdater=3.1.1
  - contourpy=1.0.5
  - coverage=7.2.2
  - cryptography=41.0.2
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.6
  - docutils=0.18.1
  - entrypoints=0.4
  - executing=0.8.3
  - filelock=3.12.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.30
  - icu=58.2
  - identify=2.5.5
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipympl=0.8.7
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.4.0
  - mdurl=0.1.0
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - munkres=1.1.4
  - myst-parser=0.18.1
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbdime=3.2.1
  - nbformat=5.7.0
  - nbstripout=0.6.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nodeenv=1.7.0
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openssl=3.0.10
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=3.10.0
  - pluggy=1.2.0
  - pre-commit=3.2.1
  - pre_commit=3.2.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyproject-api=1.5.4
  - pyrsistent=0.18.0
  - pyscaffold=4.5
  - pyscaffoldext-dsproject=0.7.2
  - pyscaffoldext-markdown=0.5
  - pysocks=1.7.1
  - pytest=7.4.0
  - pytest-cov=4.0.0
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - recommonmark=0.6.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scipy=1.11.1
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=68.0.0
  - setuptools-scm=7.1.0
  - six=1.16.0
  - smmap=4.0.0
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.3.2
  - tox=4.8.0
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ukkonen=1.0.1
  - urllib3=1.26.16
  - virtualenv=20.24.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - chainer==7.8.1
      - docopt==0.6.2
      - mizani==0.9.2
      - pipreqs==0.4.13
      - plotnine==0.12.2
      - protobuf==4.24.1
      - yarg==0.1.9
prefix: /Users/sebastiansciarra/anaconda3/envs/credit_Fraud
